import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';

const STORAGE_KEY = 'roomkh-language';

interface LanguageContextValue {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string, values?: Record<string, string | number>) => string;
}

const translations: Record<string, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.sell': 'Sell',
    'nav.about': 'About Us',
    'nav.help': 'Help',
    'nav.language': 'Language',
    'nav.selectLanguage': 'Select Language',
    'nav.changeLanguage': 'Change language, current language is {{language}}',
    'nav.switchLanguage': 'Switch language to {{language}}',
    'nav.profile': 'My Profile',
    'nav.settings': 'Settings',
    'nav.logout': 'Log Out',
    'nav.login': 'Log In',
    'nav.signup': 'Sign Up',
    'nav.toggle': 'Toggle Navigation',
    'hero.titleLine1': 'Find Your Perfect',
    'hero.titleLine2': 'Property in Cambodia',
    'hero.subtitle': 'Thousands of rooms, apartments, houses or land for rent or sale across Cambodia.',
    'hero.location': 'Location',
    'hero.searchLocation': 'Search location',
    'hero.propertyType': 'Property Type',
    'hero.selectType': 'Select Type',
    'hero.purpose': 'Purpose',
    'hero.selectPurpose': 'Select Purpose',
    'hero.forRent': 'For Rent',
    'hero.forSale': 'For Sale',
    'hero.priceRange': 'Price Range',
    'hero.priceAll': '$0 - $3,000+',
    'hero.price0to200': '$0 - $200',
    'hero.price200to500': '$200 - $500',
    'hero.price500to1500': '$500 - $1,500',
    'hero.price1500plus': '$1,500+',
    'hero.search': 'Search',
    'hero.popularSearches': 'Popular searches',
    'hero.tagRoom': 'Room',
    'hero.tagHome': 'Home',
    'hero.tagCondo': 'Condo',
    'hero.tagApartment': 'Apartment',
    'hero.tagVilla': 'Villa',
    'hero.tagLand': 'Land',
    'property.featuredTitle': 'Featured properties',
    'property.viewAll': 'View all',
    'property.loadingSlow': 'Render server is starting up, please wait a moment...',
    'property.fetchError': 'Failed to fetch properties. Server may be waking up.',
    'property.empty': 'No properties found matching your criteria.',
    'property.feature': 'Feature',
    'property.save': 'Save property',
    'property.untitled': 'Untitled Property',
    'property.defaultLocation': 'Phnom Penh, Cambodia',
    'property.bed': 'Bed',
    'property.bath': 'Bath',
    'property.month': 'month',
    'property.room': 'Room',
    'property.home': 'Home',
    'property.condo': 'Condo',
    'property.apartment': 'Apartment',
    'property.villa': 'Villa',
    'property.land': 'Land',
    'property.house': 'House',
    'property.studioRoom': 'Studio Room',
    'property.perMonth': '/ month',
    'propertyList.home': 'Home',
    'propertyList.viewAll': 'View all',
    'propertyList.propertiesFound': '{{count}} properties found',
    'propertyList.foundMatching': 'Found properties matching your search.',
    'propertyList.sortBy': 'Sort by:',
    'propertyList.newest': 'Newest',
    'propertyList.priceLowToHigh': 'Price: Low to High',
    'propertyList.priceHighToLow': 'Price: High to Low',
    'propertyList.area': 'Area',
    'propertyList.location': 'Location',
    'propertyList.searchLocation': 'Search location',
    'propertyList.propertyType': 'Property Type',
    'propertyList.selectType': 'Select Type',
    'propertyList.purpose': 'Purpose',
    'propertyList.select': 'Select',
    'propertyList.forRent': 'For Rent',
    'propertyList.forSale': 'For Sale',
    'propertyList.priceRange': 'Price Range',
    'propertyList.priceAll': '$0 - $3,000+',
    'propertyList.price0to200': '$0 - $200',
    'propertyList.price200to500': '$200 - $500',
    'propertyList.price500to1500': '$500 - $1,500',
    'propertyList.bedrooms': 'Bedrooms',
    'propertyList.any': 'Any',
    'propertyList.1bed': '1 Bed',
    'propertyList.2beds': '2 Beds',
    'propertyList.3plusBeds': '3+ Beds',
    'propertyList.bathrooms': 'Bathrooms',
    'propertyList.1bath': '1 Bath',
    'propertyList.2plusBaths': '2+ Baths',
    'propertyList.search': 'Search',
    'favorites.title': 'My Favorites',
    'favorites.subtitle': 'Properties you have saved.',
    'favorites.empty': 'No favorites yet. Browse properties and click the heart icon to save your favorites.',
    'location.title': 'Browse by location',
    'location.count': '{{count}} properties',
    'why.title': 'Why choosing RoomKH?',
    'why.verifiedTitle': 'Verified Listing',
    'why.verifiedDesc': 'Every property is verified for your peace of mind.',
    'why.pricesTitle': 'Best Prices',
    'why.pricesDesc': 'Compare prices and find the best deals.',
    'why.secureTitle': 'Secure Transactions',
    'why.secureDesc': 'Buy with confidence through trusted owners.',
    'why.supportTitle': 'Expert Support',
    'why.supportDesc': 'Our support team is ready to help throughout your journey.',
    'login.title': 'Welcome Back',
    'login.subtitle': 'Log in to access your RoomKH account',
    'login.badge': 'Search. Rent. Live Better.',
    'login.heroTitle': 'Your Complete Property Dashboard',
    'login.heroTitleAccent': 'Secured.',
    'login.heroDesc': 'The only platform you need to find your home or investment property in Cambodia.',
    'login.feature1Title': 'Smart Property Search',
    'login.feature1Desc': 'Browse, filter, and connect with verified listings across Cambodia instantly.',
    'login.feature2Title': 'Owner & Agent Tools',
    'login.feature2Desc': 'List properties, manage inquiries at scale, and track performance easily.',
    'login.feature3Title': 'Secure Access',
    'login.feature3Desc': 'End-to-end encrypted platform trusted by users and agents across the country.',
    'login.emailLabel': 'Email Address',
    'login.emailPlaceholder': 'Enter your email address',
    'login.passwordLabel': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.signIn': 'Log In',
    'login.signingIn': 'Logging in...',
    'login.or': 'OR',
    'login.googleSignIn': 'Sign in with Google',
    'login.noAccount': "Don't have an account?",
    'login.createAccount': 'Create Account',
    'login.staffHelp': 'Staff and admin assistance',
    'login.error': 'Invalid email or password. Please try again.',
    'register.badge': 'Join RoomKH Today',
    'register.heroTitle': 'Start Your Property',
    'register.heroTitleAccent': 'Journey With Us.',
    'register.heroDesc': 'Create an account to save properties, contact owners directly, or list and rent out your own spaces.',
    'register.feature1Title': 'Save & Compare Properties',
    'register.feature1Desc': 'Shortlist rooms and apartments you like and access them anytime.',
    'register.feature2Title': 'Connect With Owners Directly',
    'register.feature2Desc': 'Chat instantly via Telegram, phone, or WhatsApp with no middleman fees.',
    'register.feature3Title': 'Verified Marketplace',
    'register.feature3Desc': 'Secure, verified listings across Phnom Penh and major Cambodian cities.',
    'register.title': 'Create Account',
    'register.subtitle': 'Enter your details to register with RoomKH',
    'register.fullNameLabel': 'Full Name',
    'register.fullNamePlaceholder': 'Enter your full name',
    'register.emailLabel': 'Email Address',
    'register.emailPlaceholder': 'Enter your email address',
    'register.phoneLabel': 'Phone Number',
    'register.phonePlaceholder': 'Enter your phone number',
    'register.passwordLabel': 'Password',
    'register.passwordPlaceholder': 'Create a password',
    'register.confirmPasswordLabel': 'Confirm Password',
    'register.confirmPasswordPlaceholder': 'Re-enter your password',
    'register.agreeTerms': 'I agree to the',
    'register.termsOfService': 'Terms of Service',
    'register.and': 'and',
    'register.privacyPolicy': 'Privacy Policy',
    'register.signUp': 'Sign Up',
    'register.creatingAccount': 'Creating account...',
    'register.googleSignUp': 'Sign up with Google',
    'register.hasAccount': 'Already have an account?',
    'register.signIn': 'Log In',
    'register.passwordMismatch': 'Passwords do not match.',
    'register.mustAgree': 'You must agree to the Terms of Service and Privacy Policy.',
    'register.failed': 'Account creation failed. Please try again.',
    'sell.breadcrumb': 'Sell',
    'sell.heroTitle': 'Sell Your Property With RoomKH',
    'sell.heroDesc': 'Before you can list a property, please submit a seller request. Our team will review your information and approve your seller account so you can start listing on RoomKH.',
    'sell.adminApproval': 'Admin Approval Required',
    'sell.adminApprovalDesc': 'To keep our marketplace safe and trustworthy, all sellers must be verified before creating property listings.',
    'sell.whyTitle': 'Why Sell With RoomKH?',
    'sell.highVisibility': 'High Visibility',
    'sell.highVisibilityDesc': 'Reach thousands of buyers and renters across Cambodia every day.',
    'sell.verifiedBuyers': 'Verified Buyers',
    'sell.verifiedBuyersDesc': 'Connect only with serious, verified buyers and renters.',
    'sell.easyFast': 'Easy & Fast Process',
    'sell.easyFastDesc': 'Submit your request once and start listing after approval.',
    'sell.betterResults': 'Better Results',
    'sell.betterResultsDesc': 'Sell your property faster with high visibility and professional tools.',
    'sell.howItWorks': 'How It Works',
    'sell.submitRequest': 'Submit Request',
    'sell.submitRequestDesc': 'Fill out the seller request form with your personal information.',
    'sell.adminReview': 'Admin Review',
    'sell.adminReviewDesc': 'Our team reviews your request and supporting documents within 1-2 business days.',
    'sell.approval': 'Approval',
    'sell.approvalDesc': 'You will receive approval once your seller account has been verified.',
    'sell.createProperty': 'Create Property',
    'sell.createPropertyDesc': 'Log in and start listing properties without limits.',
    'sell.receiveInquiries': 'Receive Inquiries',
    'sell.receiveInquiriesDesc': 'Start receiving messages and viewing requests from potential buyers.',
    'sell.contactTitle': 'Contact Us For Inquiries',
    'sell.contactDesc': 'If you do not have an email or complete information, you can contact us via Telegram below:',
    'sell.contactTelegram': 'Click to contact our Telegram',
    'sell.alreadyApproved': 'Already Approved?',
    'sell.alreadyApprovedDesc': 'If your seller account is already approved, just log in and start creating property listings.',
    'sell.goToLogin': 'Go To Login',
    'sell.requestTitle': 'Seller Request Form',
    'sell.requestDesc': 'Please provide accurate information so our team can review and verify your seller account.',
    'sell.formFullName': 'Full Name',
    'sell.formFullNamePlaceholder': 'Enter your full name',
    'sell.formEmail': 'Email Address',
    'sell.formEmailPlaceholder': 'Enter your email address',
    'sell.formPhone': 'Phone Number',
    'sell.formPhonePlaceholder': 'Enter your phone number',
    'sell.formPosition': 'Position',
    'sell.formPositionSeller': 'Seller',
    'sell.formPositionAgent': 'Agent',
    'sell.formPositionOwner': 'Owner',
    'sell.formCompany': 'Company / Agency Name (Optional)',
    'sell.formCompanyPlaceholder': 'Enter your company or agency name',
    'sell.formReason': 'Why do you want to sell properties on RoomKH?',
    'sell.formReasonPlaceholder': 'Tell us more about you and your properties',
    'sell.formTerms': 'I agree to the',
    'sell.formMustAgree': 'You must agree to the terms and policies.',
    'sell.submitting': 'Submitting...',
    'sell.submitRequestBtn': 'Submit Request',
    'sell.submitSuccess': 'Your request has been submitted successfully! Our team will review it within 1-2 business days.',
    'sell.submitFailed': 'Submission failed. Please try again.',
    'sell.guidelinesTitle': 'Request Guidelines',
    'sell.guideline1': 'All sellers must be verified before creating property listings.',
    'sell.guideline2': 'Ensure all submitted information is accurate.',
    'sell.guideline3': 'Approval usually takes 1-2 business days.',
    'sell.guideline4': 'You will receive a confirmation email after approval.',
    'sell.guideline5': 'Your personal information is kept secure and private.',
    'sell.needHelpTitle': 'Need Help?',
    'sell.needHelpDesc': 'Our team is here to help you',
    'sell.liveChat': 'Live Chat',
    'sell.chatHours': 'Mon - Sun<br />8:00 AM - 8:00 PM',
    'sell.email': 'Email',
    'sell.emailAddress': 'support@roomkh.com',
    'sell.callUs': 'Call Us',
    'sell.phoneNumber': '(+855) 12 345 678',
    'about.breadcrumb': 'About Us',
    'about.title': 'About RoomKH',
    'about.desc': 'RoomKH is Cambodia\'s leading property marketplace, connecting buyers, renters, sellers, and verified owners through a secure, modern, and easy-to-use platform.',
    'about.missionTitle': 'Our Mission',
    'about.missionDesc': 'Make the Cambodian property experience seamless by providing a trusted digital marketplace where you can search, rent, buy, and sell properties safely and efficiently.',
    'about.visionTitle': 'Our Vision',
    'about.visionDesc': 'Become the #1 online property marketplace in Cambodia by delivering innovative technology, trusted services, and excellent customer experiences.',
    'about.valuesTitle': 'Our Values',
    'about.trust': 'Trust',
    'about.trustDesc': 'We believe transparency and consistency build long-lasting relationships.',
    'about.integrity': 'Integrity',
    'about.integrityDesc': 'We operate with honesty and professionalism in every relationship.',
    'about.innovation': 'Innovation',
    'about.innovationDesc': 'We continuously upgrade our platform using modern technology.',
    'about.customerFirst': 'Customer First',
    'about.customerFirstDesc': 'All features are designed to create the best possible experience for our users.',
    'about.serviceTitle': 'Our Services',
    'about.buyProperty': 'Buy Property',
    'about.buyPropertyDesc': 'Find verified rooms, apartments, and condos for sale.',
    'about.rentProperty': 'Rent Property',
    'about.rentPropertyDesc': 'Browse rental listings that match your lifestyle and budget.',
    'about.sellProperty': 'Sell Property',
    'about.sellPropertyDesc': 'Request seller access and list your property to millions of buyers.',
    'about.storyTitle': 'Our Story',
    'about.storyDesc': 'RoomKH is developed by Techcy Company, a technology company dedicated to building digital solutions. Our goal is to make the property journey in Cambodia seamless by providing a secure, modern, and easy-to-use platform that lets you buy, rent, and sell with confidence. Through continuous innovation and reliable services, we hope to make the best property search experience for everyone.',
    'help.breadcrumb': 'Help Center',
    'help.title': 'How Can We Help?',
    'help.subtitle': 'We\'re here to help! Find answers to common questions or contact our support team for assistance.',
    'help.searchPlaceholder': 'Search answers... (e.g., How do I list a property?)',
    'help.searchBtn': 'Search',
    'help.popularTopics': 'Popular Topics',
    'help.gettingStarted': 'Getting Started',
    'help.gettingStartedDesc': 'Learn how to create an account, search for properties, and get started with RoomKH.',
    'help.accountProfile': 'Account & Profile',
    'help.accountProfileDesc': 'Manage account settings, personal information, security, and notification preferences.',
    'help.paymentsBilling': 'Payments & Billing',
    'help.paymentsBillingDesc': 'Learn about payments, invoices, fees, and available payment methods.',
    'help.safetySecurity': 'Safety & Security',
    'help.safetySecurityDesc': 'Learn how RoomKH protects your account and keeps property transactions safe.',
    'help.faqTitle': 'Frequently Asked Questions',
    'help.stillNeedHelp': 'Still need help?',
    'help.teamHere': 'Our team is here to help you',
    'help.liveChat': 'Live Chat',
    'help.chatSchedule': 'Monday - Sunday<br />8:00 AM - 8:00 PM',
    'help.email': 'Email',
    'help.emailAddress': 'support@roomkh.com',
    'help.callUs': 'Call Us',
    'help.phoneNumber': '(+855) 12 345 678',
    'help.telegramSupport': 'Telegram Support',
    'help.telegramDesc': 'Chat with us instantly on Telegram',
    'help.telegramHandle': '@RoomKHSupport',
    'help.tapToChat': 'Tap to start chatting automatically.',
    'propertyDetail.breadcrumbHome': 'Home',
    'propertyDetail.breadcrumbViewAll': 'View All',
    'propertyDetail.breadcrumbDetails': 'Details',
    'propertyDetail.backToProperties': 'Back To Properties',
    'propertyDetail.share': 'Share',
    'propertyDetail.save': 'Save',
    'propertyDetail.saved': 'Saved',
    'propertyDetail.propertyId': 'Property ID',
    'propertyDetail.listedAgo': 'Listed 2 days ago',
    'propertyDetail.aboutTitle': 'About This Property',
    'propertyDetail.aboutDesc': 'Live in style in a fully furnished studio room in BKK1 Phnom Penh. This studio room has a nice living room, modern kitchen, private balcony, and large windows with city views. Located near the Russian Embassy, restaurants, cafes, schools, and public transport.',
    'propertyDetail.amenitiesTitle': 'Amenities',
    'propertyDetail.locationTitle': 'Location',
    'propertyDetail.openInMaps': 'Open In Maps',
    'propertyDetail.ownerTitle': 'Owner',
    'propertyDetail.verifiedOwner': 'Verified Owner',
    'propertyDetail.memberSince': 'Member since Jan 2022',
    'propertyDetail.responseRate': 'Response Rate 98%',
    'propertyDetail.responseTime': 'Usually replies within 1 hour',
    'propertyDetail.telegram': 'Telegram',
    'propertyDetail.call': 'Call',
    'propertyDetail.whatsapp': 'WhatsApp',
    'propertyDetail.similarTitle': 'Similar Properties',
    'propertyDetail.viewAll': 'View All',
    'propertyDetail.loadError': 'Failed to load this property. Please try again later.',
    'propertyDetail.notFound': 'Property not found.',
    'filter.filters': 'Filters',
    'filter.active': 'Active',
    'filter.reset': 'Reset',
    'filter.searchPlaceholder': 'Search by keyword, location, or building name...',
    'filter.location': 'Location',
    'filter.allLocations': 'All Locations',
    'filter.propertyType': 'Property Type',
    'filter.allTypes': 'All Types',
    'filter.purpose': 'Purpose',
    'filter.anyPurpose': 'Any Purpose',
    'filter.minPrice': 'Min Price ($)',
    'filter.maxPrice': 'Max Price ($)',
    'filter.resetFilters': 'Reset Filters',
    'footer.explore': 'Explore',
    'footer.buy': 'Buy',
    'footer.rent': 'Rent',
    'footer.sell': 'Sell',
    'footer.location': 'Location',
    'footer.company': 'Company',
    'footer.aboutUs': 'About Us',
    'footer.careers': 'Careers',
    'footer.contactUs': 'Contact Us',
    'footer.partnerWithUs': 'Partner With Us',
    'footer.support': 'Support',
    'footer.helpCenter': 'Help Center',
    'footer.faqs': 'FAQs',
    'footer.termsConditions': 'Terms & Conditions',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.contact': 'Contact',
    'footer.address': 'Phnom Penh, Cambodia',
    'footer.phone': '+855 12 345 678',
    'footer.email': 'roomKH@gmail.com',
    'footer.desc': "Cambodia's trusted property marketplace connecting buyers, renters, sellers, and verified owners.",
    'footer.rights': '© 2026 RoomKH. All rights reserved.',
    'footer.madeWith': 'Made with',
    'footer.inCambodia': 'in Cambodia',
  },
  km: {
    'nav.home': 'ទំព័រដើម',
    'nav.sell': 'លក់',
    'nav.about': 'អំពីយើង',
    'nav.help': 'ជំនួយ',
    'nav.language': 'ភាសា',
    'nav.selectLanguage': 'ជ្រើសរើសភាសា',
    'nav.changeLanguage': 'ប្តូរភាសា ភាសាបច្ចុប្បន្នគឺ {{language}}',
    'nav.switchLanguage': 'ប្តូរទៅភាសា {{language}}',
    'nav.profile': 'ប្រវត្តិរូបខ្ញុំ',
    'nav.settings': 'ការកំណត់',
    'nav.logout': 'ចាកចេញ',
    'nav.login': 'ចូលគណនី',
    'nav.signup': 'ចុះឈ្មោះ',
    'nav.toggle': 'បើក/បិទម៉ឺនុយ',
    'hero.titleLine1': 'ស្វែងរកអចលនទ្រព្យ',
    'hero.titleLine2': 'ដ៏ស័ក្តិសមនៅកម្ពុជា',
    'hero.subtitle': 'មានបន្ទប់ អាផាតមិន ផ្ទះ និងដីជាច្រើនសម្រាប់ជួល ឬលក់នៅទូទាំងកម្ពុជា។',
    'hero.location': 'ទីតាំង',
    'hero.searchLocation': 'ស្វែងរកទីតាំង',
    'hero.propertyType': 'ប្រភេទអចលនទ្រព្យ',
    'hero.selectType': 'ជ្រើសរើសប្រភេទ',
    'hero.purpose': 'គោលបំណង',
    'hero.selectPurpose': 'ជ្រើសរើសគោលបំណង',
    'hero.forRent': 'សម្រាប់ជួល',
    'hero.forSale': 'សម្រាប់លក់',
    'hero.priceRange': 'ចន្លោះតម្លៃ',
    'hero.priceAll': '$0 - $3,000+',
    'hero.price0to200': '$0 - $200',
    'hero.price200to500': '$200 - $500',
    'hero.price500to1500': '$500 - $1,500',
    'hero.price1500plus': '$1,500+',
    'hero.search': 'ស្វែងរក',
    'hero.popularSearches': 'ការស្វែងរកពេញនិយម',
    'hero.tagRoom': 'បន្ទប់',
    'hero.tagHome': 'ផ្ទះ',
    'hero.tagCondo': 'ខុនដូ',
    'hero.tagApartment': 'អាផាតមិន',
    'hero.tagVilla': 'វីឡា',
    'hero.tagLand': 'ដី',
    'property.featuredTitle': 'អចលនទ្រព្យពិសេស',
    'property.viewAll': 'មើលទាំងអស់',
    'property.loadingSlow': 'ម៉ាស៊ីនមេកំពុងចាប់ផ្តើម សូមរង់ចាំបន្តិច...',
    'property.fetchError': 'មិនអាចទាញយកអចលនទ្រព្យបានទេ។ ម៉ាស៊ីនមេប្រហែលកំពុងចាប់ផ្តើម។',
    'property.empty': 'រកមិនឃើញអចលនទ្រព្យតាមលក្ខខណ្ឌរបស់អ្នកទេ។',
    'property.feature': 'ពិសេស',
    'property.save': 'រក្សាទុកអចលនទ្រព្យ',
    'property.untitled': 'អចលនទ្រព្យគ្មានចំណងជើង',
    'property.defaultLocation': 'ភ្នំពេញ កម្ពុជា',
    'property.bed': 'គ្រែ',
    'property.bath': 'បន្ទប់ទឹក',
    'property.month': 'ខែ',
    'property.room': 'បន្ទប់',
    'property.home': 'ផ្ទះ',
    'property.condo': 'ខុនដូ',
    'property.apartment': 'អាផាតមិន',
    'property.villa': 'វីឡា',
    'property.land': 'ដី',
    'property.house': 'ផ្ទះ',
    'property.studioRoom': 'បន្ទប់ស្ទូឌីយោ',
    'property.perMonth': '/ ខែ',
    'propertyList.home': 'ទំព័រដើម',
    'propertyList.viewAll': 'មើលទាំងអស់',
    'propertyList.propertiesFound': 'រកឃើញអចលនទ្រព្យ {{count}}',
    'propertyList.foundMatching': 'រកឃើញអចលនទ្រព្យតាមលក្ខខណ្ឌស្វែងរករបស់អ្នក។',
    'propertyList.sortBy': 'តម្រៀបតាម៖',
    'propertyList.newest': 'ថ្មីបំផុត',
    'propertyList.priceLowToHigh': 'តម្លៃ៖ ទាបទៅខ្ពស់',
    'propertyList.priceHighToLow': 'តម្លៃ៖ ខ្ពស់ទៅទាប',
    'propertyList.area': 'តំបន់',
    'propertyList.location': 'ទីតាំង',
    'propertyList.searchLocation': 'ស្វែងរកទីតាំង',
    'propertyList.propertyType': 'ប្រភេទអចលនទ្រព្យ',
    'propertyList.selectType': 'ជ្រើសរើសប្រភេទ',
    'propertyList.purpose': 'គោលបំណង',
    'propertyList.select': 'ជ្រើសរើស',
    'propertyList.forRent': 'សម្រាប់ជួល',
    'propertyList.forSale': 'សម្រាប់លក់',
    'propertyList.priceRange': 'ចន្លោះតម្លៃ',
    'propertyList.priceAll': '$0 - $3,000+',
    'propertyList.price0to200': '$0 - $200',
    'propertyList.price200to500': '$200 - $500',
    'propertyList.price500to1500': '$500 - $1,500',
    'propertyList.bedrooms': 'ចំនួនបន្ទប់គេង',
    'propertyList.any': 'ណាមួយ',
    'propertyList.1bed': '1 គ្រែ',
    'propertyList.2beds': '2 គ្រែ',
    'propertyList.3plusBeds': '3+ គ្រែ',
    'propertyList.bathrooms': 'ចំនួនបន្ទប់ទឹក',
    'propertyList.1bath': '1 បន្ទប់ទឹក',
    'propertyList.2plusBaths': '2+ បន្ទប់ទឹក',
    'propertyList.search': 'ស្វែងរក',
    'favorites.title': 'អចលនទ្រព្យដែលបានរក្សាទុក',
    'favorites.subtitle': 'អចលនទ្រព្យដែលអ្នកបានរក្សាទុក។',
    'favorites.empty': 'មិនមានអចលនទ្រព្យដែលបានរក្សាទុកទេ។ សូមរកមើលអចលនទ្រព្យ និងចុចសញ្ញាប្រាក់ច្រវាក់ដើម្បីរក្សាទុក។',
    'location.title': 'ស្វែងរកតាមទីតាំង',
    'location.count': 'អចលនទ្រព្យ {{count}}',
    'why.title': 'ហេតុអ្វីជ្រើសរើស RoomKH?',
    'why.verifiedTitle': 'បញ្ជីបានផ្ទៀងផ្ទាត់',
    'why.verifiedDesc': 'អចលនទ្រព្យទាំងអស់ត្រូវបានផ្ទៀងផ្ទាត់ ដើម្បីឱ្យអ្នកមានទំនុកចិត្ត។',
    'why.pricesTitle': 'តម្លៃល្អបំផុត',
    'why.pricesDesc': 'ប្រៀបធៀបតម្លៃ និងស្វែងរកជម្រើសដែលសមស្របបំផុត។',
    'why.secureTitle': 'ប្រតិបត្តិការមានសុវត្ថិភាព',
    'why.secureDesc': 'ទិញដោយទំនុកចិត្តតាមរយៈម្ចាស់ដែលអាចជឿទុកចិត្តបាន។',
    'why.supportTitle': 'ជំនួយពីអ្នកជំនាញ',
    'why.supportDesc': 'ក្រុមជំនួយរបស់យើងរួចរាល់ជួយអ្នកពេញមួយដំណើរ។',
    'login.title': 'ស្វាងមកវិញ',
    'login.subtitle': 'ចូលគណនីដើម្បីចូលប្រើប្រាស់គណនី RoomKH របស់អ្នក',
    'login.badge': 'ស្វែងរក. ជួល. រស់នៅល្អប្រសើរ',
    'login.heroTitle': 'ផ្ទាំងព័ត៌មានអចលនទ្រព្យពេញលេញរបស់អ្នក',
    'login.heroTitleAccent': 'ធានាសុវត្ថិភាព.',
    'login.heroDesc': 'វេទិកាតែមួយសម្រាប់អ្នកស្វែងរកផ្ទះ និងក្រុមដ្ឋានដ្ឋានគ្រោងទ្រឹងទុកដោយសុវត្ថិភាព និងងាយស្រួល។',
    'login.feature1Title': 'ការស្វែងរកអចលនទ្រព្យឆ្លាតវៃ',
    'login.feature1Desc': 'រកមើល ត្រង និងទំនាក់ទំនងបញ្ជីបានផ្ទៀងផ្ទាត់នៅកម្ពុជាភ្លាមៗ។',
    'login.feature2Title': 'ឧបករណ៍ម្ចាស់ផ្ទះ និងភ្នាក់ងារ',
    'login.feature2Desc': 'បញ្ចូលអចលនទ្រព្យ គ្រប់គ្រងការបន្ទាន់កម្រិតខ្ពស់ និងតាមដានសំឡឹងមកវិញ។',
    'login.feature3Title': 'ចូលប្រើប្រាស់ផ្លូវការសុវត្ថិភាព',
    'login.feature3Desc': 'ការអ៊ិនក្រ។បន្ទាប់ផ្សំដែលទុកចិត្តបានសុវត្ថិភាពសម្រាប់អ្នកប្រើប្រាស់និងបុគ្គលិកទាំងអស់។',
    'login.emailLabel': 'អាស័យដ្ឋានអ៊ីមែល',
    'login.emailPlaceholder': 'បញ្ចូលអាស័យដ្ឋានអ៊ីមែលរបស់អ្នក',
    'login.passwordLabel': 'ពាក្យសម្ងាត់',
    'login.passwordPlaceholder': 'បញ្ចូលពាក្យសម្ងាត់របស់អ្នក',
    'login.rememberMe': 'ចងចាំខ្ញុំ',
    'login.forgotPassword': 'ភ្លេចពាក្យសម្ងាត់?',
    'login.signIn': 'ចូលគណនី',
    'login.signingIn': 'កំពុងចូលគណនី...',
    'login.or': 'ឬ',
    'login.googleSignIn': 'ចូលគណនីជាមួយ Google',
    'login.noAccount': 'មិនមានគណនីទេ?',
    'login.createAccount': 'បង្កើតគណនី',
    'login.staffHelp': 'ជំនួយបុគ្គលិក និងអ្នកគ្រប់គ្រង',
    'login.error': 'អាស័យដ្ឋានអ៊ីមែល ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ។ សូមព្យាយាមម្តងទៀត។',
    'register.badge': 'ចូលរួម RoomKH ថ្ងៃនេះ',
    'register.heroTitle': 'ចាប់ផ្តើមដំណើរអចលនទ្រព្យ',
    'register.heroTitleAccent': 'របស់អ្នកជាមួយយើង។',
    'register.heroDesc': 'បង្កើតគណនីដើម្បីរក្សាទុកអចលនទ្រព្យ ទំនាក់ទំនងម្ចាស់ផ្ទះដោយផ្ទាល់ ឬដាក់សំឡឹងលក់និងជួលទីតាំងរបស់អ្នក។',
    'register.feature1Title': 'រក្សាទុក និងប្រៀបធៀបអចលនទ្រព្យ',
    'register.feature1Desc': 'ចំណាំបន្ទប់ និងអាផាតមិនចំណុចចេញរបស់អ្នកដើម្បីចូលប្រើប្រាស់គ្រប់ពេល។',
    'register.feature2Title': 'ទំនាក់ទំនងម្ចាស់ផ្ទះដោយផ្ទាល់',
    'register.feature2Desc': 'តភ្ជាប់ភ្លាមៗតាម Telegram ទូរស័ព្ទ ឬ WhatsApp ដោយគ្មានសេចក្តីថ្លៃថ្លៃកណ្តាល។',
    'register.feature3Title': 'ទីផ្សារដែលបានផ្ទៀងផ្ទាត់',
    'register.feature3Desc': 'បញ្ជីសុវត្ថិភាពនិងបានផ្ទៀងផ្ទាត់នៅទូទាំងរាជធានីភ្នំពេញនិងទីក្រុងធំៗរបស់កម្ពុជា។',
    'register.title': 'បង្កើតគណនី',
    'register.subtitle': 'បញ្ចូលព័ត៌មានរបស់អ្នកដើម្បីចុះឈ្មោះជាមួយ RoomKH',
    'register.fullNameLabel': 'ឈ្មោះពេញ',
    'register.fullNamePlaceholder': 'បញ្ចូលឈ្មោះពេញរបស់អ្នក',
    'register.emailLabel': 'អាស័យដ្ឋានអ៊ីមែល',
    'register.emailPlaceholder': 'បញ្ចូលអាស័យដ្ឋានអ៊ីមែលរបស់អ្នក',
    'register.phoneLabel': 'លេខទូរស័ព្ទ',
    'register.phonePlaceholder': 'បញ្ចូលលេខទូរស័ព្ទរបស់អ្នក',
    'register.passwordLabel': 'ពាក្យសម្ងាត់',
    'register.passwordPlaceholder': 'បង្កើតពាក្យសម្ងាត់',
    'register.confirmPasswordLabel': 'បញ្ជាក់ពាក្យសម្ងាត់',
    'register.confirmPasswordPlaceholder': 'បញ្ចូលពាក្យសម្ងាត់ម្តងទៀត',
    'register.agreeTerms': 'ខ្ញុំយល់ព្រមនឹង',
    'register.termsOfService': 'លក្ខខណ្ឌសេវាកម្ម',
    'register.and': 'និង',
    'register.privacyPolicy': 'គោលការណ៍ឯកជនភាព',
    'register.signUp': 'ចុះឈ្មោះ',
    'register.creatingAccount': 'កំពុងបង្កើតគណនី...',
    'register.googleSignUp': 'ចុះឈ្មោះជាមួយ Google',
    'register.hasAccount': 'មានគណនីហើយ?',
    'register.signIn': 'ចូលគណនី',
    'register.passwordMismatch': 'ពាក្យសម្ងាត់មិនផ្គូផ្គង។',
    'register.mustAgree': 'អ្នកត្រូវតែយល់ព្រមនឹងលក្ខខណ្ឌសេវាកម្ម និងគោលការណ៍ឯកជនភាព។',
    'register.failed': 'បរាជ័យក្នុងការបង្កើតគណនី។ សូមព្យាយាមម្តងទៀត។',
    'sell.breadcrumb': 'លក់',
    'sell.heroTitle': 'លក់អចលនទ្រព្យរបស់អ្នកជាមួយ RoomKH',
    'sell.heroDesc': 'មុនពេលអ្នកអាចបញ្ចូលអចលនទ្រព្យរបស់អ្នកបាន សូមដាក់សំឡឹងសំណើលក់។ ក្រុមគ្រប់គ្រងរបស់យើងនឹងពិនិត្យព័ត៌មានរបស់អ្នក និងអនុញ្ញាតគណនីរបស់អ្នកដើម្បីអ្នកអាចចាប់ផ្តើមបញ្ចូលអចលនទ្រព្យនៅលើ RoomKH។',
    'sell.adminApproval': 'ទាមទា�់ការអនុញ្ញាតពីអ្នកគ្រប់គ្រង',
    'sell.adminApprovalDesc': 'ដើម្បីរក្សាទីផ្សាររបស់យើងមានសុវត្ថិភាព និងទុកចិត្តបាន អ្នកលក់ទាំងអស់ត្រូវតែត្រូវបានផ្ទៀងផ្ទាត់មុនពេលបង្កើតបញ្ជីអចលនទ្រព្យ។',
    'sell.whyTitle': 'ហេតុអ្វីលក់ជាមួយ RoomKH?',
    'sell.highVisibility': 'ការមើលឃើញខ្ពស់',
    'sell.highVisibilityDesc': 'ដល់រហូតដល់ម៉ឺននាក់អ្នកទិញស្វែងរកអចលនទ្រព្យនៅទូទាំងកម្ពុជារាល់ថ្ងៃ។',
    'sell.verifiedBuyers': 'អ្នកទិញបានផ្ទៀងផ្ទាត់',
    'sell.verifiedBuyersDesc': 'តភ្ជាប់តែអ្នកទិញពិតជានិងបានផ្ទៀងផ្ទាត់ប៉ុណ្ណោះ។',
    'sell.easyFast': 'ដំណើរការងាយៗ និងរហ័ស',
    'sell.easyFastDesc': 'ដាក់សំឡឹងសំណើរបស់អ្នកម្តងហើយចាប់ផ្តើមបញ្ចូលបញ្ជីបន្ទាប់ពីទទួលបានការអនុញ្ញាត។',
    'sell.betterResults': 'លទ្ធផលល្អប្រសើរ',
    'sell.betterResultsDesc': 'លក់អចលនទ្រព្យរបស់អ្នករហ័សជាង ដោយការមើលឃើញខ្ពស់ និងឧបករណ៍វិជ្ជាជីវៈ។',
    'sell.howItWorks': 'វិធីដំណើរការ',
    'sell.submitRequest': 'ដាក់សំឡឹងសំណើ',
    'sell.submitRequestDesc': 'បំពេញទម្រង់សំណើលក់ជាមួយព័ត៌មានផ្ទាល់ខ្លួនរបស់អ្នក។',
    'sell.adminReview': 'ការពិនិត្យពីអ្នកគ្រប់គ្រង',
    'sell.adminReviewDesc': 'ក្រុមរបស់យើងពិនិត្យសំណើ និងឯកសារគាំទ្ររបស់អ្នកក្នុងរយៈពេលធ្វើការ 1-2 ថ្ងៃ។',
    'sell.approval': 'ការអនុញ្ញាត',
    'sell.approvalDesc': 'អ្នកនឹងទទួលបានការអនុញ្ញាតក្រោយពេលគណនីលក់របស់អ្នកត្រូវបានអនុញ្ញាត។',
    'sell.createProperty': 'បង្កើតអចលនទ្រព្យ',
    'sell.createPropertyDesc': 'ចូលគណនី និងបញ្ចូលបញ្ជីអចលនទ្រព្យគ្មានដែនកំណត់។',
    'sell.receiveInquiries': 'ទទួលសំឡឹងមកវិញ',
    'sell.receiveInquiriesDesc': 'ចាប់ផ្តើមទទួលសារនិងសំណើមើលពីអ្នកទិញដែលអាចចង់បាន។',
    'sell.contactTitle': 'អ្នកអាចទំនាក់ទំនងមកយើងខ្ញុំសម្រាប់សំណើ',
    'sell.contactDesc': 'ប្រសិនបើអ្នកមិនមានអាស័យដ្ឋានអ៊ីមែល ឬព័ត៌មានមិនពេញលេញ អ្នកអាចទំនាក់ទំនងមកយើងខ្ញុំតាម Telegram ខាងក្រោម៖',
    'sell.contactTelegram': 'ចុចទៅកាន់ទំនាក់ទំនង Telegram របស់យើង',
    'sell.alreadyApproved': 'ត្រូវបានអនុញ្ញាតហើយ?',
    'sell.alreadyApprovedDesc': 'ប្រសិនបើគណនីលក់របស់អ្នកត្រូវបានអនុញ្ញាតហើយ គ្រាន់តែចូលគណនីហើយចាប់ផ្តើមបង្កើតបញ្ជីអចលនទ្រព្យ។',
    'sell.goToLogin': 'ទៅទំព័រចូលគណនី',
    'sell.requestTitle': 'សំណើលក់ និងជួលអចលនទ្រព្យរបស់អ្នក',
    'sell.requestDesc': 'សូមផ្ដល់ព័ត៌មានត្រឹមត្រូវដើម្បីក្រុមរបស់យើងអាចពិនិត្យ និងផ្ទៀងផ្ទាត់គណនីលក់របស់អ្នក។',
    'sell.formFullName': 'ឈ្មោះពេញ',
    'sell.formFullNamePlaceholder': 'បញ្ចូលឈ្មោះពេញរបស់អ្នក',
    'sell.formEmail': 'អាស័យដ្ឋានអ៊ីមែល',
    'sell.formEmailPlaceholder': 'បញ្ចូលអាស័យដ្ឋានអ៊ីមែលរបស់អ្នក',
    'sell.formPhone': 'លេខទូរស័ព្ទ',
    'sell.formPhonePlaceholder': 'បញ្ចូលលេខទូរស័ព្ទរបស់អ្នក',
    'sell.formPosition': 'តំណែង',
    'sell.formPositionSeller': 'អ្នកលក់',
    'sell.formPositionAgent': 'ភ្នាក់ងារ',
    'sell.formPositionOwner': 'ម្ចាស់',
    'sell.formCompany': 'ឈ្មោះអាជីវកម្ម / ក្រុមហ៊ុន (ស្រេចចិត្ត)',
    'sell.formCompanyPlaceholder': 'បញ្ចូលឈ្មោះអាជីវកម្ម ឬក្រុមហ៊ុនរបស់អ្នក',
    'sell.formReason': 'ហេតុអ្វីបានជាអ្នកចង់លក់អចលនទ្រព្យនៅលើ RoomKH?',
    'sell.formReasonPlaceholder': 'ប្រាប់យើងខ្ញុំបន្ថែមអំពីអ្នក និងអចលនទ្រព្យរបស់អ្នក',
    'sell.formTerms': 'ខ្ញុំយល់ព្រមនឹងលក្ខខណ្ឌ និងគោលការណ៍ឯកជនភាព',
    'sell.formMustAgree': 'អ្នកត្រូវតែយល់ព្រមនឹងលក្ខខណ្ឌ និងគោលការណ៍។',
    'sell.submitting': 'កំពុងដាក់សំឡឹង...',
    'sell.submitRequestBtn': 'ដាក់សំឡឹងសំណើ',
    'sell.submitSuccess': 'សំណើរបស់អ្នកត្រូវបានដាក់សំឡឹងដោយជោគជ័យ! ក្រុមរបស់យើងនឹងពិនិត្យក្នុងរយៈពេលធ្វើការ 1-2 ថ្ងៃ។',
    'sell.submitFailed': 'បរាជ័យក្នុងការដាក់សំឡឹង។ សូមព្យាយាមម្តងទៀត។',
    'sell.guidelinesTitle': 'ជំនួយសំណើ',
    'sell.guideline1': 'អ្នកលក់ទាំងអស់ត្រូវតែទទួលបានការអនុញ្ញាតមុនពេលបញ្ចូលបញ្ជីអចលនទ្រព្យ។',
    'sell.guideline2': 'ធានាថាព័ត៌មានដែលបានដាក់សំឡឹងមានត្រឹមត្រូវ។',
    'sell.guideline3': 'ការអនុញ្ញា�តជាទូទៅចំណាយពេលធ្វើការ 1-2 ថ្ងៃ។',
    'sell.guideline4': 'អ្នកនឹងទទួលបានអ៊ីមែលបញ្ជាក់បន្ទាប់ពីទទួលបានការអនុញ្ញាត។',
    'sell.guideline5': 'ព័ត៌មានផ្ទាល់ខ្លួនរបស់អ្នកត្រូវបានរក្សាទុកដោយសុវត្ថិភាព និងភាពឯកជនភាព។',
    'sell.needHelpTitle': 'ត្រូវការជំនួយ?',
    'sell.needHelpDesc': 'ក្រុមរបស់យើងនៅទីនេះដើម្បីជួយអ្នក',
    'sell.liveChat': 'ជជែកផ្ទាល់',
    'sell.chatHours': 'ច័ន្ទ - អាទិត្យ<br />8:00 ព្រឹក - 8:00 ល្ងាច',
    'sell.email': 'អ៊ីមែល',
    'sell.emailAddress': 'support@roomkh.com',
    'sell.callUs': 'ហៅយើង',
    'sell.phoneNumber': '(+855) 12 345 678',
    'about.breadcrumb': 'អំពីយើង',
    'about.title': 'អំពី RoomKH',
    'about.desc': 'RoomKH ជាទីផ្សារអចលនទ្រព្យដំណាត់ក្រុងរបស់កម្ពុជា តភ្ជាប់អ្នកទិញ អ្នកជួល អ្នកលក់ និងម្ចាស់អចលនទ្រព្យដែលបានផ្ទៀងផ្ទាត់តាមរយៈវេទិកាសុវត្ថិភាព ទំនើប និងងាយស្រួល។',
    'about.missionTitle': 'បេសកកម្មរបស់យើង',
    'about.missionDesc': 'ធ្វើឱ្យបទពិសោធន៍អចលនទ្រព្យរបស់កម្ពុជាមានភាពស្មុគស្មាញដោយផ្តល់ទីផ្សារឌីជីថលដែលទុកចិត្តបាន ដែលអ្នកអាចស្វែងរក ជួល ទិញ និងលក់អចលនទ្រព្យដោយសុវត្ថិភាព និងប្រសិទ្ធភាព។',
    'about.visionTitle': 'ចក្ខុវិស័យរបស់យើង',
    'about.visionDesc': 'ក្លាយជាវេទិកាអចលនទ្រព្យអនឡាញដំណាត់ក្រុងរបស់កម្ពុជាដោយផ្តល់បច្ចេកវិទ្យាថ្មីៗ សេវាកម្មទុកចិត្តបាន និងបទពិសោធន៍អតិថិជនល្អប្រសើរ។',
    'about.valuesTitle': 'តម្លៃរបស់យើង',
    'about.trust': 'ទំនុកចិត្ត',
    'about.trustDesc': 'យើងជឿជាក់ថាភាពច្សាប់សម្ងាត់ជាអត្រាសាច់គ្នាដែលបង្កើតទំនាក់ទំនងយូរអង្វែង។',
    'about.integrity': 'ភាពឆ្នើម',
    'about.integrityDesc': 'យើងធ្វើការដោយស្មោះត្រង់ និងទះវិជ្ជាជីវៈនៅក្នុងទំនាក់ទំនងទាំងអស់។',
    'about.innovation': 'ការច្នៃប្រតិបត្តិ',
    'about.innovationDesc': 'យើងធ្វើបច្ចុប្បន្នភាពវេទិការបស់យើងជានិច្ចដោយប្រើបច្ចេកវិទ្យាទំនើប។',
    'about.customerFirst': 'អតិថិជនជាមុនសំខាន់',
    'about.customerFirstDesc': 'មុខងារទាំងអស់ត្រូវបានរចនាឡើងដើម្បីបង្កើតបទពិសោធន៍ល្អប្រសើរសម្រាប់អ្នកប្រើប្រាស់របស់យើង។',
    'about.serviceTitle': 'សេវាកម្មរបស់យើង',
    'about.buyProperty': 'ទិញអចលនទ្រព្យ',
    'about.buyPropertyDesc': 'ស្វែងរកបន្ទប់ អាផាតមិន និងខុនដូដែលបានផ្ទៀងផ្ទាត់សម្រាប់លក់។',
    'about.rentProperty': 'ជួលអចលនទ្រព្យ',
    'about.rentPropertyDesc': 'រកមើលបញ្ជីជួលដែលសមនឹងរបៀបរស់នៅ និងថ្លៃសំណាក់របស់អ្នក។',
    'about.sellProperty': 'លក់អចលនទ្រព្យ',
    'about.sellPropertyDesc': 'សុំការអនុញ្ញាតអ្នកលក់ និងបញ្ចូលអចលនទ្រព្យរបស់អ្នកទៅកាន់ម៉ឺននាក់អ្នកទិញ។',
    'about.storyTitle': 'រឿងរ៉ាវរបស់យើង',
    'about.storyDesc': 'RoomKH ត្រូវបានអភិវឌ្ឍដោយ Techcy Company ក្រុមហ៊ុនបច្ចេកវិទ្យាដែលប្តេជ្ញាក្នុងការបង្កើតដំណោះស្រាយឌីជីថលច្នៃប្រតិបត្តិ។ គោលដៅរបស់យើងគឺធ្វើឱ្យដំណើរអចលនទ្រព្យនៅកម្ពុជាមានភាពស្មុគស្មាញដោយផ្តល់វេទិកាសុវត្ថិភាព ទំនើប និងងាយប្រើ ដែលអ្នកអាចទិញ ជួល និងលក់អចលនទ្រព្យដោយទំនុកចិត្ត។ តាមរយៈការច្នៃប្រតិបត្តិជានិច្ច និងសេវាកម្មដែលអាចទុកចិត្តបាន យើងសង្ឃឹមថានឹងធ្វើឱ្យការស្វែងរកអចលនទ្រព្យល្អបំផុតសម្រាប់គ្រប់គ្នា។',
    'help.breadcrumb': 'មជ្ឈមណ្ឌលជំនួយ',
    'help.title': 'យើងអាចជួយអ្នកយ៉ាងដូចមេ?',
    'help.subtitle': 'យើងនៅទីនេះដើម្បីជួយអ្នក! ស្វែងរកចម្លើយសំរាប់សំណួរទូទៅ ឬទំនាក់ទំនងក្រុមជំនួយរបស់យើងសម្រាប់ជំនួយ។',
    'help.searchPlaceholder': 'ស្វែងរកចម្លើយ... (ឧទាហរណ៍ ធ្វើដូចម្ដេចដើម្បីបញ្ចូលអចលនទ្រព្យ?)',
    'help.searchBtn': 'ស្វែងរក',
    'help.popularTopics': 'ប្រធានបទពេញនិយម',
    'help.gettingStarted': 'ចាប់ផ្តើម',
    'help.gettingStartedDesc': 'រៀនពីរបៀបបង្កើតគណនី រកមើលអចលនទ្រព្យ និងចាប់ផ្តើមជាមួយ RoomKH។',
    'help.accountProfile': 'គណនី និងប្រវត្តិរូប',
    'help.accountProfileDesc': 'គ្រប់គ្រងការកំណត់គណនី ព័ត៌មានផ្ទាល់ខ្លួន សុវត្ថិភាព និងចំណង់ចំណូលចិត្តការជូនដំណឹង។',
    'help.paymentsBilling': 'ការទូទាត់ និងវិក្កយបត្រ',
    'help.paymentsBillingDesc': 'រៀនអំពីការទូទាត់ វិក្កយបត្រ ថ្លៃសេវា និងវិធីសាស្ត្រទូទាត់ដែលមាន។',
    'help.safetySecurity': 'សុវត្ថិភាព និងការពារ',
    'help.safetySecurityDesc': 'រៀនពីរបៀប RoomKH ការពារគណនីរបស់អ្នក និងរក្សាសុវត្ថិភាពប្រតិបត្តិការអចលនទ្រព្យ។',
    'help.faqTitle': 'សំណួរពេញនិយម',
    'help.stillNeedHelp': 'ត្រូវការជំនួយទៀត?',
    'help.teamHere': 'ក្រុមរបស់យើងនៅទីនេះដើម្បីជួយអ្នក',
    'help.liveChat': 'ជជែកផ្ទាល់',
    'help.chatSchedule': 'ច័ន្ទ - អាទិត្យ<br />8:00 ព្រឹក - 8:00 ល្ងាច',
    'help.email': 'អ៊ីមែល',
    'help.emailAddress': 'support@roomkh.com',
    'help.callUs': 'ហៅយើង',
    'help.phoneNumber': '(+855) 12 345 678',
    'help.telegramSupport': 'ជំនួយតាម Telegram',
    'help.telegramDesc': 'ជជែកជាមួយយើងភ្លាមៗតាម Telegram',
    'help.telegramHandle': '@RoomKHSupport',
    'help.tapToChat': 'ចុចដើម្បីចាប់ផ្តើមជជែកដោយស្វ័យប្រវត្តិ។',
    'propertyDetail.breadcrumbHome': 'ទំព័រដើម',
    'propertyDetail.breadcrumbViewAll': 'មើលទាំងអស់',
    'propertyDetail.breadcrumbDetails': 'ព័ត៌មានលម្អិត',
    'propertyDetail.backToProperties': 'ត្រឡប់ទៅអចលនទ្រព្យ',
    'propertyDetail.share': 'ចែករំលែក',
    'propertyDetail.save': 'រក្សាទុក',
    'propertyDetail.saved': 'បានរក្សាទុក',
    'propertyDetail.propertyId': 'លេខសម្គាល់អចលនទ្រព្យ',
    'propertyDetail.listedAgo': 'បានបញ្ជីពី 2 ថ្ងៃមុន',
    'propertyDetail.aboutTitle': 'អំពីអចលនទ្រព្យនេះ',
    'propertyDetail.aboutDesc': 'រស់នៅទីក្រុងដោយស្ករតាន់ក្នុងបន្ទប់ស្ទូឌីយោមួយគ្រែដែលរះបាន់នៅ BKK1 ភ្នំពេញ។ បន្ទប់ស្ទូឌីយោនេះមានបន្ទប់រស់នៅរះបាន់ ផ្ទះបាយទំនើប បាលោខប្លាក និងបង្អួចធំដែលមើលឃើញទេសភាពទីក្រុងស្រស់ស្អាត។ ស្ថិតនៅជិតម៉ូលទំនាក់ទំនង ភោជនីយដ្ឋាន កាហ្វេ សាលារៀន និងការធ្វើដំណើរសាធារណៈ។',
    'propertyDetail.amenitiesTitle': 'សេវាកម្ម',
    'propertyDetail.locationTitle': 'ទីតាំង',
    'propertyDetail.openInMaps': 'បើកនៅក្នុងផែនទី',
    'propertyDetail.ownerTitle': 'ម្ចាស់',
    'propertyDetail.verifiedOwner': 'ម្ចាស់បានផ្ទៀងផ្ទាត់',
    'propertyDetail.memberSince': 'សមាជិកតាំងពីខែមករា 2022',
    'propertyDetail.responseRate': 'អត្រាឆ្លើយតប 98%',
    'propertyDetail.responseTime': 'ពេលឆ្លើយតបជាធម្មតាឆ្លើយក្នុងរយៈពេល 1 ម៉ោង',
    'propertyDetail.telegram': 'Telegram',
    'propertyDetail.call': 'ហៅ',
    'propertyDetail.whatsapp': 'WhatsApp',
    'propertyDetail.similarTitle': 'អចលនទ្រព្យដែលស្រដៀង',
    'propertyDetail.viewAll': 'មើលទាំងអស់',
    'propertyDetail.loadError': 'មិនអាចផ្ទុកអចលនទ្រព្យនេះបានទេ។ សូមព្យាយាមម្តងទៀត។',
    'propertyDetail.notFound': 'មិនឃើញអចលនទ្រព្យ។',
    'filter.filters': 'ត្រង',
    'filter.active': 'សកម្ម',
    'filter.reset': 'កំណត់ឡើងវិញ',
    'filter.searchPlaceholder': 'ស្វែងរកតាមពាក្យគន្លឹះ ទីតាំង ឬឈ្មោះអគារ...',
    'filter.location': 'ទីតាំង',
    'filter.allLocations': 'ទីតាំងទាំងអស់',
    'filter.propertyType': 'ប្រភេទអចលនទ្រព្យ',
    'filter.allTypes': 'ប្រភេទទាំងអស់',
    'filter.purpose': 'គោលបំណង',
    'filter.anyPurpose': 'គោលបំណងណាមួយ',
    'filter.minPrice': 'តម្លៃអប្បបុរស ($)',
    'filter.maxPrice': 'តម្លៃអតិបរមា ($)',
    'filter.resetFilters': 'កំណត់ត្រងឡើងវិញ',
    'footer.explore': 'រុករក',
    'footer.buy': 'ទិញ',
    'footer.rent': 'ជួល',
    'footer.sell': 'លក់',
    'footer.location': 'ទីតាំង',
    'footer.company': 'ក្រុមហ៊ុន',
    'footer.aboutUs': 'អំពីយើង',
    'footer.careers': 'ឱកាសធ្វើការ',
    'footer.contactUs': 'ទំនាក់ទំនងមកយើង',
    'footer.partnerWithUs': 'ដៃគូជាមួយយើង',
    'footer.support': 'ជំនួយ',
    'footer.helpCenter': 'មជ្ឈមណ្ឌលជំនួយ',
    'footer.faqs': 'សំណួរពេញនិយម',
    'footer.termsConditions': 'លក្ខខណ្ឌ និងខ្សឹប',
    'footer.privacyPolicy': 'គោលការណ៍ឯកជនភាព',
    'footer.contact': 'ទំនាក់ទំនង',
    'footer.address': 'ភ្នំពេញ កម្ពុជា',
    'footer.phone': '+855 12 345 678',
    'footer.email': 'roomKH@gmail.com',
    'footer.desc': "ទីផ្សារអចលនទ្រព្យទុកចិត្តបានរបស់កម្ពុជាដែលតភ្ជាប់អ្នកទិញ អ្នកជួល អ្នកលក់ និងម្ចាស់អចលនទ្រព្យ។",
    'footer.rights': '© 2026 RoomKH. រក្សាសិទ្ធិទាំងអស់។',
    'footer.madeWith': 'បង្កើតដោយ',
    'footer.inCambodia': 'នៅកម្ពុជា',
  },
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function interpolate(
  template: string,
  values: Record<string, string | number> = {}
): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => String(values[key] ?? ''));
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<string>(
    () => localStorage.getItem(STORAGE_KEY) || 'en'
  );

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => {
    const t = (key: string, values?: Record<string, string | number>) => {
      const template =
        translations[language]?.[key] || translations.en[key] || key;
      return interpolate(template, values);
    };

    return { language, setLanguage, t };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextValue {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
